name: Build Executable

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install customtkinter
        pip install requests
        
    - name: Build executable
      run: |
        pyinstaller --onefile App.py server.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-artifact
        path: dist/ddns.exe  # Replace with the path to your generated .exe file